### ISSUE TITLE
Asus Security app detects Aptoide as malware

### ISSUE THREAD

**Issue by henriquedesousa** [Aptoide/aptoide-client-v8#122]
When running Aptoide on ASUS tablet with latest ROM, the following message appears.

![unnamed](https://user-images.githubusercontent.com/12630569/27637864-20bfa216-5c09-11e7-9617-18de7e3784aa.jpg)

By clicking ignore we can still run Aptoide, although next time the message will appear again.

Many thanks in advance

**Comment by jdandrade** [comment]
Hello @henriquedesousa, hope everything is going well with you!

We are archiving old issues so we can focus on the new ones coming from recent releases.

Until now we did not respond efficiently to any github issue and did not look to it as an official issue tracking system and we are sorry for it - we get most of the feedback through our zendesk platform. This will change as we will keep track of any new issues that arrive here and answer any questions.

This issue will be archived. 

If you need anything feel free to open a new ticket. Also we are glad to announce that we recently released the first v9 version of Aptoide that can be found in rmota's store inside Aptoide.

Thank you for the feedback.

Best regards,
João Andrade
