### ISSUE TITLE
Aptoide mobile app not working...

### ISSUE THREAD

**Issue by xmha97** [Aptoide/aptoide-client-v8#1305]
Hello,
Aptoide is not working but Aptoide TV working fine.
I also used a VPN but the mobile app didn't work.
Why?

Aptoide Mobile:
![Aptoide Mobile](https://user-images.githubusercontent.com/23485114/77408149-2c68ee00-6daf-11ea-99bc-cb1645b77ee2.png)

Aptoide TV:
![Aptoide TV](https://user-images.githubusercontent.com/23485114/77408299-6afea880-6daf-11ea-8c9d-9860d33e6d8c.png)

**Comment by jdandrade** [comment]
Hello @xmha97 

I assume you are using the latest version: 9.13.2.1?

Did you ever get it working or it is the first time that you are using Aptoide mobile version on that phone?

**Comment by xmha97** [comment]
Yes, I use the last version. (downloaded from GitHub)
![Aptoide](https://user-images.githubusercontent.com/23485114/77414115-68548100-6db8-11ea-833d-6a438b16b7be.png)
I disabled the Google play store and always using Aptoide

**Comment by xmha97** [comment]
The latest version that working on my device is version 9.13.0.0
![Aptoide](https://user-images.githubusercontent.com/23485114/77417029-ad7ab200-6dbc-11ea-9cfa-f81ff65252a7.png)
Please the fix issue.

**Comment by jdandrade** [comment]
Do any of the other tabs work? Editorial, Search, Stores, Apps?

**Comment by xmha97** [comment]
Hello
No, none of the tabs work.

**Comment by jdandrade** [comment]
Can you try our nightly version to see if the same happens? https://aptoide-dev.en.aptoide.com/app

**Comment by xmha97** [comment]
I don't have a problem right now, but I don't know what the problem was.
Everything is working fine now. 🤗
