### ISSUE TITLE
VLC on Aptoide is outdated version

### ISSUE THREAD

**Issue by xmha97** [Aptoide/aptoide-client-v8#1310]
Hello
I see an outdated version of VLC on Aptoide.
Please remove this version and add it to the blacklist.
![Aptoide](https://user-images.githubusercontent.com/23485114/78948045-5d9a2b80-7adc-11ea-86b1-e3be38f75e27.jpg)

**Comment by jdandrade** [comment]
Thanks for the report. Will request its removal.

**Comment by jdandrade** [comment]
Version removed. thanks for the report 👍

**Comment by xmha97** [comment]
OK, Thanks <3
