### ISSUE TITLE
Upload Apps

### ISSUE THREAD

**Issue by xmha97** [Aptoide/aptoide-client-v8#1318]
Hello,
Why can't upload some apps?
![Android Notification Bar](https://user-images.githubusercontent.com/23485114/79289167-d3880380-7edd-11ea-8b2a-e7f6062daff3.png)

**Comment by jdandrade** [comment]
Some apps are only distributable by the developer through Catappult, which is a platform we work with.

**Comment by xmha97** [comment]
That is, can only the developer update the program?

**Comment by jdandrade** [comment]
In these cases, yes.
