### ISSUE TITLE
Can't log in to Aptoide 

### ISSUE THREAD

**Issue by xmha97** [Aptoide/aptoide-client-v8#1325]
Hello, I Can't log in to Aptoide
Please help me.

![Aptoide TV](https://user-images.githubusercontent.com/23485114/80295477-238d8280-8788-11ea-8928-67a0089c3788.png)

![Aptoide](https://user-images.githubusercontent.com/23485114/80295474-1ff9fb80-8788-11ea-822c-2bce7e64dda2.png)

**Comment by jdandrade** [comment]
We are currently undergoing major changes to our authentication system.

https://blog.aptoide.com/aptoide-new-authentication-system-no-user-data-storage/
