### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by TacoTheDank** [Aptoide/aptoide-client-v8#1366]
There's 514 branches, most of which are stale. Could some of them maybe be cleaned up / deleted please?

**Comment by jdandrade** [comment]
Yes, will do some cleaning.

**Comment by TacoTheDank** [comment]
Awesome, looks quite better. Thanks!

**Comment by TacoTheDank** [comment]
@jdandrade Apologies for asking on a closed issue, but could the same be done for https://github.com/Aptoide/aptoide-uploader as well?
