### ISSUE TITLE
"Apps" tab doesn't work!

### ISSUE THREAD

**Issue by xmha97** [Aptoide/aptoide-client-v8#1408]
Hi,
The "Apps" tab doesn't work!
![image](https://user-images.githubusercontent.com/23485114/94981289-d1723980-053d-11eb-8715-c44026e16d89.png)
Please watch the below video:
https://i.imgur.com/ISvdfVo.mp4
Thanks.

**Comment by jdandrade** [comment]
Can you update to the latest version? 9.17.1.0 we soft released yesterday.

**Comment by xmha97** [comment]
I downloaded the latest version from GitHub and now everything works very well.
