### ISSUE TITLE
App don't work, like offline

### ISSUE THREAD

**Issue by Pierrot69** [Aptoide/aptoide-client-v8#1422]
Hello, I have a problem with my app.  when i run it it looks like it is not connected to the internet, like the app is offline.  The loading logo remains indefinitely for all categories, and crash on stores.
 
I tried several solutions:
- install and uninstall the app
- Downgrade the app
- Reboot phone
- On wifi / Flight mode / mobile network
- wipe dalvik cache / cache

![Screenshot_20201112-073540](https://user-images.githubusercontent.com/74343555/98904385-c81fa980-24b9-11eb-8f3f-8ac3d3171b9c.jpg)

![Screenshot_20201112-071946](https://user-images.githubusercontent.com/74343555/98904300-9e668280-24b9-11eb-8948-1ed8e20cfdee.jpg)

**Comment by jdandrade** [comment]
Can you give us more information about the device? Brand, model and Android OS version

**Comment by Pierrot69** [comment]
The device is a Oneplus 5 (A5000) and it's Rooted
The version of the Android OS is 10.0.0

**Comment by Pierrot69** [comment]
Okay i solve the problem !
I uninstall aptoide ans install this version : 9.10.0.0 (9961)
And after that i update the app, it seems to work now
