### ISSUE TITLE
Why this project soo idle? and i cannot access to translation site :/

### ISSUE THREAD

**Issue by pYFZOS5** [Aptoide/aptoide-client-v8#1451]
In the readme, there's a link for translation project http://translate.aptoide.com/
why unable access to the project?

**Comment by jdandrade** [comment]
Hello, we moved our translations to another framework some time ago. 

If you are interested in participating in the translations project for the Aptoide App Store app, please contact carlos.garrido@aptoide.com

**Comment by pYFZOS5** [comment]
I sent mail to mentioned address and this repository last activity, 2020 nov. it make bit scary but if you also have moved it to another platform, it's ok 🤪

**Comment by pYFZOS5** [comment]
@jdandrade any update?

**Comment by jdandrade** [comment]
This repo is still being maintained. Will update master branch after next release, which should happen soon.

**Comment by pYFZOS5** [comment]
>If you are interested in participating in the translations project for the Aptoide App Store app, please contact carlos.garrido@aptoide.com

@jdandrade i still didn't receive any reply from mentioned address and it seems aptoide keep localization project bit closed from public. in this case, it may affect to future volunteer contributions.
about repo, thank you for the details.
