### ISSUE TITLE
Show just FOSS Apps Option

### ISSUE THREAD

**Issue by maverick74** [Aptoide/aptoide-client-v8#348]
Please consider adding an option to the Aptoide client (which could be off by default) where one can say it only wants to see FOSS apps (Apps that use GPL, MIT, Etc licenses)

Another good addition would be a place where the licence, if there is one, would be shown

Thank you

**Comment by jdandrade** [comment]
Hello.

This FOSS filter feature will be taken in as a suggestion and will be discussed in the future.

We are archiving old issues so we can focus on the new ones coming from recent releases.

Until now we did not respond efficiently to any github issue and did not look to it as an official issue tracking system and we are sorry for it - we get most of the feedback through our zendesk platform. This will change as we will keep track of any new issues that arrive here and answer any questions.

This issue will be archived. 

If you need anything feel free to open a new ticket. Also we are glad to announce that we recently released the first v9 version of Aptoide that can be found in rmota's store inside Aptoide.

Thank you for the feedback.

Best regards,
João Andrade
