### ISSUE TITLE
show error

### ISSUE THREAD

**Issue by lmdevs** [Aptoide/aptoide-client-v8#368]
it was showing some error
![screenshot 29](https://user-images.githubusercontent.com/29618151/33490225-727e3f9c-d6dc-11e7-9120-eee10e7e40a3.png)

**Comment by jdandrade** [comment]
Hello.

We are archiving old issues so we can focus on the new ones coming from recent releases.

Until now we did not respond efficiently to any github issue and did not look to it as an official issue tracking system and we are sorry for it - we get most of the feedback through our zendesk platform. This will change as we will keep track of any new issues that arrive here and answer any questions.

This issue will be archived. 

If you need anything feel free to open a new ticket. Also we are glad to announce that we recently released the first v9 version of Aptoide that can be found in rmota's store inside Aptoide.

Thank you for the feedback.

Best regards,
João Andrade
