### ISSUE TITLE
[9.x] Refreshing app list displays 2 reload icons

### ISSUE THREAD

**Issue by ldmpub** [Aptoide/aptoide-client-v8#701]
![double reload icon](https://user-images.githubusercontent.com/1452146/45448081-cab3c800-b6d1-11e8-82d3-8ef29e0c234f.png)

I'm quite sure only one icon is sufficient.

**Comment by jdandrade** [comment]
Hello ldmpub,

Thank you for your feedback. One icon is indeed sufficient :)
We will re-visit the Apps menu view soon. 
We will make sure we will look into this and get the changes out in a near future release.

Thank you very much for noticing in this type of details.

Best,
JA

**Comment by jdandrade** [comment]
Hello ldmpub, 

Thank you for your feedback.

Can you confirm if this only happens because the Apps menu is taking too much time to load in your device?

I agree that we need to look into this problem. In a near future we will review this layout and handle this case. The view should not take time to load.

Best regards,
JA

**Comment by ldmpub** [comment]
Hi, you're right: this screen was displayed for "ages" (at least for several minutes) despite my Wifi connection was very fast! It took not only time to display this screen (with double reload) but also later to update apps.

Best regards,

**Comment by jdandrade** [comment]
Thank you for the answer.
The slowness is something that we are working on at the moment. As soon as we do it, we will re-check if we still need to make this layout changes, because this view shouldn't need time to load. 

Best regards,
JA

**Comment by ldmpub** [comment]
As far as I understand, you are making a link between my UI issue reported above and an already known technical / performance issue see#588.

**Comment by jdandrade** [comment]
Yes, this issue is connected to #588. I will close this one so we merge all related conversations into one thread.
