### ISSUE TITLE
[Translation] Help to find a string

### ISSUE THREAD

**Issue by ldmpub** [Aptoide/aptoide-client-v8#703]
Hi,

I'm trying to improve the french translation of Aptoide app: there is a lot of work ;-( and it's a hard work because in crowdin screenshots are not always available to check context.

Can someone point me to the string "Commentaire" which should be changed to a verb (it's an action) "Commenter" ... see:
![new action](https://user-images.githubusercontent.com/1452146/45486917-0ba4ee80-b75d-11e8-9d53-81d04135b9bc.jpg)

**Comment by jdandrade** [comment]
Hello ldmpub,

The string you are talking about has this id (or context in crowdin): dialog_button_comment

Best regards,
JA

**Comment by ldmpub** [comment]
Great, it's corrected.

Who can approve this translation change? see https://crowdin.com/translate/aptoide-mobile/all/en-fr#q=dialog_button_comment

Note: there is a "context's screen shot" for this string but this translation is wrong since the beginning (8 months), thanks to translator "Aptoide_Official" ;-).
