### ISSUE TITLE
Can you publish the apk in the release section?

### ISSUE THREAD

**Issue by John3** [Aptoide/aptoide-client-v8#989]
Hi

Why is not published the apk in the release section? What is the differences with the aptoide website apk?

BTW all the source of the client in this repo is the same as the apk? I mean is completely open source?

thx

**Comment by jdandrade** [comment]
Hello @John3 

> Why is not published the apk in the release section?

You are right, I will ask to update latest release with the apk download, future releases will also have the apk.

> What is the differences with the aptoide website apk?

This release will be first available here and in an Aptoide in-app store named rmota. In both places you will have the earliest taste of the latest release. We only expose the apk on those places to lower the exposition and to monitor the apk until we know it is stable enough to go to the Website. 
It can take 1-2 weeks to get to the website - so you will usually see a lower version in the website compared to the one here.

> BTW all the source of the client in this repo is the same as the apk? I mean is completely open source? 

Yes. 

I will update you when we get the apk in the latest release (can only do it tomorrow) - only then I will consider this issue closed. If you have any questions let us know meanwhile.

**Comment by jdandrade** [comment]
Hello @John3 
Latest APK was uploaded to the release section. I will close this issue, if you need anything else - open a new issue.
